### ISSUE TITLE
make check fails for cortexa53

### ISSUE THREAD

**Issue by jfikar** [flame/blis#329]
Hello,

I was trying to compile blis on aarch64 Raspberry Pi4, which has cortex-a72. Everything works for cortexa57 including make check. BTW. it works also on Raspberry Pi3, which has cortex-a53.

With cortexa53 it is build fine, bud make check fails with a segmentation fault:

```
Compiling obj/cortexa53/testsuite/test_xpbym.o
Compiling obj/cortexa53/testsuite/test_xpbyv.o
Linking test_libblis.x against 'lib/cortexa53/libblis.a -fopenmp -lm -lpthread -lrt'
Running test_libblis.x (fast) with output redirected to 'output.testsuite'
bash: line 2:  7799 Segmentation fault      ./test_libblis.x -g ./testsuite/input.general.fast -o ./testsuite/input.operations.fast > output.testsuite
make: *** [Makefile:828: testsuite-run-fast] Error 139

```
I'm using recent Debian Buster for aarch64.

**Comment by fgvanzee** [comment]
This is weird. The `cortexa53` and `cortexa57` configurations are basically identical:
```
$ diff -u config/cortexa53/make_defs.mk config/cortexa57/make_defs.mk 
--- config/cortexa53/make_defs.mk	2019-02-12 16:05:48.929618000 -0600
+++ config/cortexa57/make_defs.mk	2019-02-12 16:05:48.936573000 -0600
@@ -35,7 +35,7 @@
 
 # Declare the name of the current configuration and add it to the
 # running list of configurations included by common.mk.
-THIS_CONFIG    := cortexa53
+THIS_CONFIG    := cortexa57
 #CONFIGS_INCL   += $(THIS_CONFIG)
 
 #
@@ -57,13 +57,13 @@
 ifeq ($(DEBUG_TYPE),noopt)
 COPTFLAGS      := -O0
 else
-COPTFLAGS      := -O3 -ftree-vectorize -mtune=cortex-a53
+COPTFLAGS      := -O3 -ftree-vectorize -mtune=cortex-a57
 endif
 
 # Flags specific to optimized kernels.
 CKOPTFLAGS     := $(COPTFLAGS)
 ifeq ($(CC_VENDOR),gcc)
-CKVECFLAGS     := -march=armv8-a+fp+simd -mcpu=cortex-a53
+CKVECFLAGS     := -march=armv8-a+fp+simd -mcpu=cortex-a57
 else
 $(error gcc is required for this configuration.)
 endif
```
The `bli_cntx_init_cortexa53.c`/`bli_cntx_init_cortexa57.c` have trivial differences (related to the configuration name). And `bli_family_cortexa53.h`/`bli_family_cortexa57.h` are both effectively empty.

Any ideas, @dnparikh, @figual?

**Comment by jfikar** [comment]
I have tried to run gdb on the testing program and it gives more details about the segmentation fault:

```
gdb -ex=r --args ./test_libblis.x -g ./testsuite/input.general.fast -o ./testsuite/input.operations.fast
GNU gdb (Debian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./test_libblis.x...(no debugging symbols found)...done.
Starting program: /home/pi/blis-0.6.0/test_libblis.x -g ./testsuite/input.general.fast -o ./testsuite/input.operations.fast
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
% detected -g option; using "./testsuite/input.general.fast" for parameters filename.
% detected -o option; using "./testsuite/input.operations.fast" for operations filename.

Program received signal SIGSEGV, Segmentation fault.
0x00000055555b4ae0 in bli_gks_query_cntx_noinit ()
(gdb)
```

**Comment by fgvanzee** [comment]
This helps. Could you recompile with debugging enabled and optimization disabled, and then run `gdb` again? (`./configure -d noopt ...`) A full stack trace would also be ideal (Just run `bt` command in `gdb`).

**Comment by jfikar** [comment]
Here is the trace:

```
Program received signal SIGSEGV, Segmentation fault.
bli_gks_lookup_ind_cntx (id=BLIS_ARCH_CORTEXA53, ind=BLIS_NAT) at frame/base/bli_gks.c:285
285             cntx_t*  restrict gks_id_ind = gks_id[ ind ];
(gdb) bt
#0  bli_gks_lookup_ind_cntx (id=BLIS_ARCH_CORTEXA53, ind=BLIS_NAT) at frame/base/bli_gks.c:285
#1  0x0000005555ae2774 in bli_gks_lookup_nat_cntx (id=BLIS_ARCH_CORTEXA53) at frame/base/bli_gks.c:258
#2  0x0000005555ae2a28 in bli_gks_query_cntx_noinit () at frame/base/bli_gks.c:438
#3  0x0000005555c0ae98 in bli_ind_init () at frame/ind/bli_ind.c:57
#4  0x0000005555b04ec4 in bli_init_apis () at frame/base/bli_init.c:79
#5  0x0000007fbf5f2250 in __pthread_once_slow (once_control=0x5556ff6e98 <once_init>, init_routine=0x5555b04eb4 <bli_init_apis>) at pthread_once.c:116
#6  0x0000005555c65b44 in bli_pthread_once (once=0x5556ff6e98 <once_init>, init=0x5555b04eb4 <bli_init_apis>) at frame/thread/bli_pthread.c:314
#7  0x0000005555b04f18 in bli_init_once () at frame/base/bli_init.c:104
#8  0x0000005555c9a5ec in bli_thread_get_num_threads () at frame/thread/bli_thread.c:1294
#9  0x0000005555735238 in libblis_test_output_params_struct (os=0x7fbf5c6588 <_IO_2_1_stdout_>, params=0x7fffffeba0) at testsuite/src/test_libblis.c:807
#10 0x0000005555734d2c in libblis_test_read_params_file (input_filename=0x5556ff75b0 <libblis_test_parameters_filename> "./testsuite/input.general.fast", 
    params=0x7fffffeba0) at testsuite/src/test_libblis.c:638
#11 0x0000005555733464 in main (argc=5, argv=0x7fffffed78) at testsuite/src/test_libblis.c:77
(gdb) 
```

**Comment by figual** [comment]
This should be fixed now in bfddf671328e7e372ac7228f72ff2d9d8e03ae18.

**Comment by jfikar** [comment]
I can confirm that it works now. However I got some errors in out.cblat2. Not sure if it is important. All other tests passed.

```
...
CTBMV  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .167333    ,    .442557    )  (    .167333    ,    .442557    )
       2  (    .217320    ,    .108337    )  (    .217320    ,    .108337    )
       3  (    .329789    ,   -.166362E-01)  (    .329789    ,   -.166362E-01)
       4  (    .250089    ,   -.910139E-01)  (   -.609890E+10,   -.275225E+10)
       5  (    .796754    ,   -.565034E-01)  (    .796754    ,   -.565034E-01)
 ******* CTBMV  FAILED ON CALL NUMBER:
    747: CTBMV ('L','N','U',  5,  4, A,  6, X, 2)                               .

 CTPMV  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .686813    ,   -.156843    )  (    .686813    ,   -.156843    )
       2  (   -.101935    ,    .100522    )  (   -.101935    ,    .100522    )
       3  (   -.365189E-01,    .520084E-01)  (   -.365189E-01,    .520084E-01)
       4  (    .305346    ,    .135281    )  (   -.529970E+10,    .843656E+10)
       5  (    .884216    ,    .264764    )  (    .884216    ,    .264764    )
 ******* CTPMV  FAILED ON CALL NUMBER:
    171: CTPMV ('L','N','U',  5, AP, X, 2)                                      .

 CTRSV  PASSED THE TESTS OF ERROR-EXITS

 CTRSV  PASSED THE COMPUTATIONAL TESTS (   241 CALLS)

 CTBSV  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .749251E-02,    .242757    )  (   -32.3105    ,    128.059    )
       2  (     .00000    ,     .00000    )  (    .349610E-01,   -.424232    )
       3  (    .167333    ,    .306693    )  (   -.229271E+10,   -.484016E+10)
       4  (    .796703    ,    .298701    )  (    .796703    ,    .298701    )
       5  (    .127373    ,   -.356643    )  (    .127373    ,   -.356643    )
 ******* CTBSV  FAILED ON CALL NUMBER:
    723: CTBSV ('U','N','U',  5,  4, A,  6, X, 2)                               .

 CTPSV  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .926573    ,   -.356643    )  (    .160330    ,    .189820    )
       2  (     .00000    ,     .00000    )  (    .683755E-01,    .389953E-01)
       3  (    .117383    ,    .498502    )  (   -.271229E+10,   -.426074E+10)
       4  (    .247253    ,    .429570E-01)  (    .247253    ,    .429570E-01)
       5  (    .774226E-01,   -.348651    )  (    .774226E-01,   -.348651    )
 ******* CTPSV  FAILED ON CALL NUMBER:
    147: CTPSV ('U','N','U',  5, AP, X, 2)                                      .

 CGERC  PASSED THE TESTS OF ERROR-EXITS
...
```

On the other hand, for cortexa57 all tests passed ok, strange.

**Comment by jfikar** [comment]
Ok, I see.
Thank you
